### ISSUE TITLE
Package import structure

### ISSUE THREAD

**Issue by jknox13** [erichson/ristretto#12]
Currently the entire package is 'flattened' meaning that you can import any function
in any module of the package directly by:
```
from ristretto import <function>
```
This is more or less equivalent to writing the entire package in a single file,
and may be undesirable especially because of namespace confusion.

As of now, ``from ristretto import dmd`` imports the function ``dmd``
from the ``dmd`` module within the package, not the ``dmd`` module. In addition
to being confusing, this prevents a user from importing the ``dmd`` module at all,
ie:

```
from ristretto import dmd
...
standard_result = dmd.dmd(A)
random_result = dmd.rdmd(A)
```

To accomplish the above, the user as of now must:

```
import ristretto as ro
...
standard_result = ro.dmd(A)
random_result = ro.rdmd(A)
```
Which is fine if the package only has a few modules containing a couple functions
each, but it becomes much less manageable as modules are added.

In the end this comes down to the following:
1. Will the package only contain a handful of matrix factorization functions
or
2. Will modules be added to the package that add new or different sets of methods
(i.e. randomized graphical methods like randomized min cut or randomized regression
techniques). Additionally, will the current modules be extended to include different
computational paradigms (i.e. parallel methods or limited precision methods).

If ``1``, the flattening is fine, but if any part of ``2`` is wanted in the future,
I think it is best that we spend some time rethinking the package import structure.

**Comment by erichson** [comment]
This is an excellent comment. The idea is it to provide different computational paradigms in a future version. Hence, we should switch to ``2``.
