### ISSUE TITLE
Installation and usage failures

### ISSUE THREAD

**Issue by gwgundersen** [erichson/ristretto#31]
This looks like a great project, but I've had a couple problems trying to install and use ristretto based on the documentation. I'm on macOS 10.13.4. First, I tried to simply `pip install` it, but it failed because of a Cython dependency issue. I installed Cython, and the installation still failed, throwing errors like,

    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/gwg/miniconda3/envs/ele538b/include -arch x86_64 -I/Users/gwg/miniconda3/envs/ele538b/include -arch x86_64 -I/Users/gwg/miniconda3/envs/ele538b/include/python3.7m -c ristretto/nmf/_fhals_update.c -o build/temp.macosx-10.7-x86_64-3.7/ristretto/nmf/_fhals_update.o
    ristretto/nmf/_fhals_update.c:16255:21: error: no member named 'exc_type' in 'struct _ts'
        *type = tstate->exc_type;
                ~~~~~~  ^

Eventually I got a `fatal error: too many errors emitted`, and the installation process crashed.

So then I cloned the directory and ran `setup.py` instead, which almost worked, but I also had to install `sckit-learn` before I could import it. Now I can import the module, but I get errors when importing specific functions, e.g.:

    ImportError: cannot import name 'rlu' from 'ristretto.lu' (/Users/gwg/miniconda3/envs/ele538b/lib/python3.7/site-packages/ristretto-0.1.2-py3.7.egg/ristretto/lu.py)

I apologize for the broad request, but could the maintainers please clean up the installation process or advise if I'm doing something wrong? Thanks.

**Comment by jknox13** [comment]
Hi @gwgundersen,

Our apologies, we have been actively updating the package a lot recently and have failed to keep the README up to date with the API changes.

Hopefully the installation procedure and API behavior is clear now. Please continue to open Issues if you run into other troubles.
