### ISSUE TITLE
LinAlgError exceptions

### ISSUE THREAD

**Issue by aoguedao** [erichson/ristretto#40]
I have a little error about LinAlgError exception in eigen decompositions like compute_reigh_nystroem. 
The error message is: `NameError: name 'LinAlgError' is not defined`

I think it should be

`try:
    blabla
except linalg.LinAlgError:
    blabla
`

instead of 
`try:
    blabla
except LinAlgError:
    blabla
`

I'm working in a linux container using docker in Windows 10.
- Python 3.7.6
- numpy 1.18.5
- scipy 1.4.1
Is it necessary give more info about my hardware/software?

OffTopic: Is it repository unmantained?

**Comment by erichson** [comment]
@aoguedao let me double check and get back to you soon.

**Comment by aoguedao** [comment]
Thanks @erichson! This could help me a lot with my thesis :)

**Comment by erichson** [comment]
@aoguedao  can you try:
```
pip uninstall ristretto
pip install git+https://github.com/erichson/ristretto
```

**Comment by aoguedao** [comment]
Hi @erichson !

The last commit fixed `compute_reigh_nystroem_col` but not `compute_reigh_nystroem` :(

PS: I've been using `A = - np.identity(3` because it is not a positive definite matrix

**Comment by erichson** [comment]
@aoguedao sorry for that. I should be fixed now. :)

**Comment by aoguedao** [comment]
Nice! thank you @erichson :)
