### ISSUE TITLE
Supported Distributions

### ISSUE THREAD

**Issue by jknox13** [erichson/ristretto#7]
Standardize the set of sampling distributions. As of now we use the following:
- 'guassian' or 'normal': ``np.random.standard_normal``
- 'uniform': ``np.random.uniform(-1, 1)``
- 'None': ``np.random.rand``
And also from ``csvd``
- 'spixel': random sampling of rows
- 'sparse': ``np.sparse.rand``

After we agree on the set of sampling distributions, we can incorporate them into
the ``sketch`` function to reduce code repetition and limit the set of distributions
on an algorithm by algorithm basis if needed (i.e. if ``rsvd`` and ``rdmd``
should not have the same set of distributions available).

**Comment by erichson** [comment]
Yes, that is a great idea to unify the sketch functionality across all functions. It will us also allow to easily add some additional sketching schemes in a future version.
