### ISSUE TITLE
Algorithm standard output

### ISSUE THREAD

**Issue by jknox13** [erichson/ristretto#9]
Replace ``print()`` functions within algorithms with either:
- ``logging.<log_level>()``
- ``warnings.<warn_level>()``
where appropriate, specified by user ``verbosity`` or ``verbose`` keyword arguments.

**Comment by erichson** [comment]
Sounds good.

**Comment by Ohjeah** [comment]
Seems like this has been done in 0e05cf2f2af04c24da5f3168e88c82527e20fa26.
